In [2]:
import pandas
from datetime import datetime
from pytz import utc

data = pandas.read_csv("files/reviews.csv", parse_dates=['Timestamp'])
data.head()

,Course Name,Timestamp,Rating,Comment
0,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 06:25:52+00:00,4.0,NaN
1,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 05:12:34+00:00,4.0,NaN
2,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 05:11:03+00:00,4.0,NaN
3,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 03:33:24+00:00,5.0,NaN
4,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 03:31:49+00:00,4.5,NaN

In [4]:
day_average = data.groupby(['Timestamp'])
day_average.head()

,Course Name,Timestamp,Rating,Comment
0,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 06:25:52+00:00,4.0,NaN
1,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 05:12:34+00:00,4.0,NaN
2,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 05:11:03+00:00,4.0,NaN
3,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 03:33:24+00:00,5.0,NaN
4,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 03:31:49+00:00,4.5,NaN
...,...,...,...,...
44995,Python for Beginners with Examples,2018-01-01 01:11:26+00:00,4.0,NaN
44996,The Python Mega Course: Build 10 Real World Ap...,2018-01-01 01:09:56+00:00,5.0,NaN
44997,The Python Mega Course: Build 10 Real World Ap...,2018-01-01 01:08:11+00:00,5.0,NaN
44998,Python for Beginners with Examples,2018-01-01 01:05:26+00:00,5.0,NaN
44999,The Python Mega Course: Build 10 Real World Ap...,2018-01-01 01:01:16+00:00,5.0,NaN

In [8]:
day_average = data.groupby(['Course Name'])
day_average.head()

,Course Name,Timestamp,Rating,Comment
0,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 06:25:52+00:00,4.0,NaN
1,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 05:12:34+00:00,4.0,NaN
2,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 05:11:03+00:00,4.0,NaN
3,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 03:33:24+00:00,5.0,NaN
4,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 03:31:49+00:00,4.5,NaN
10,The Complete Python Course: Build 10 Professio...,2021-04-01 18:56:12+00:00,4.0,NaN
12,100 Python Exercises I: Evaluate and Improve Y...,2021-04-01 15:03:17+00:00,4.5,NaN
13,The Complete Python Course: Build 10 Professio...,2021-04-01 13:56:49+00:00,4.0,NaN
18,100 Python Exercises I: Evaluate and Improve Y...,2021-04-01 09:00:03+00:00,4.5,NaN
19,100 Python Exercises I: Evaluate and Improve Y...,2021-04-01 08:47:42+00:00,4.5,Excellent set of practical problems. Thank you!
27,Interactive Data Visualization with Python and...,2021-04-01 03:52:44+00:00,5.0,NaN
29,The Complete Python Course: Build 10 Professio...,2021-04-01 02:52:05+00:00,4.0,NaN
31,The Complete Python Course: Build 10 Professio...,2021-04-01 01:32:52+00:00,5.0,NaN
34,The Complete Python Course: Build 10 Professio...,2021-03-31 22:53:04+00:00,5.0,NaN
36,100 Python Exercises I: Evaluate and Improve Y...,2021-03-31 22:15:57+00:00,4.5,NaN
40,Interactive Data Visualization with Python and...,2021-03-31 20:58:08+00:00,5.0,NaN
47,100 Python Exercises I: Evaluate and Improve Y...,2021-03-31 15:20:17+00:00,5.0,NaN
55,Interactive Data Visualization with Python and...,2021-03-31 10:47:17+00:00,4.0,NaN
60,Python for Beginners with Examples,2021-03-31 07:21:59+00:00,5.0,really enjoying it so far
74,Python for Beginners with Examples,2021-03-30 16:18:04+00:00,5.0,NaN
79,Interactive Data Visualization with Python and...,2021-03-30 14:02:10+00:00,4.5,NaN
80,Data Processing with Python,2021-03-30 13:27:17+00:00,3.5,NaN
88,Python for Beginners with Examples,2021-03-30 07:29:05+00:00,5.0,NaN
93,Data Processing with Python,2021-03-30 05:50:45+00:00,4.0,NaN
100,Python for Beginners with Examples,2021-03-30 01:01:55+00:00,4.0,NaN
110,Data Processing with Python,2021-03-29 14:58:59+00:00,3.5,NaN
116,100 Python Exercises II: Evaluate and Improve ...,2021-03-29 13:22:19+00:00,4.0,NaN
117,Interactive Data Visualization with Python and...,2021-03-29 13:13:57+00:00,5.0,NaN
121,Data Processing with Python,2021-03-29 11:16:36+00:00,5.0,NaN
122,Data Processing with Python,2021-03-29 11:13:28+00:00,3.5,NaN
136,Python for Beginners with Examples,2021-03-28 14:23:29+00:00,3.0,NaN
156,Learn GIS in One Hour,2021-03-27 20:28:21+00:00,5.0,NaN
395,Learn GIS in One Hour,2021-03-19 13:27:01+00:00,2.5,NaN
424,100 Python Exercises II: Evaluate and Improve ...,2021-03-18 11:56:38+00:00,4.5,NaN
488,100 Python Exercises II: Evaluate and Improve ...,2021-03-16 10:07:22+00:00,5.0,NaN
527,Learn GIS in One Hour,2021-03-14 16:54:51+00:00,5.0,I am really greatful for the lessons .Ardit is...
600,Learn GIS in One Hour,2021-03-11 21:38:23+00:00,4.0,NaN
616,100 Python Exercises II: Evaluate and Improve ...,2021-03-11 14:25:39+00:00,5.0,NaN
689,100 Python Exercises II: Evaluate and Improve ...,2021-03-09 01:48:25+00:00,4.5,"I solve, the better concept I understood."
835,Learn GIS in One Hour,2021-03-03 20:48:51+00:00,5.0,NaN